//$file${.::Nodo3_SM.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: blinky_console.qm
// File:  ${.::Nodo3_SM.c}
//
// This code has been generated by QM 6.1.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::Nodo3_SM.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "Nodo3_SM.h"
#include "qpc.h"    // QP/C real-time embedded framework
#include "bsp.h"    // Board Support Package interface

#include "board.h"
#include "peripherals.h"
#include "pin_mux.h"
#include "clock_config.h"
#include "MKL46Z4.h"
#include "fsl_debug_console.h"

#include "Nodo3_QP.h"

// ask QM to declare the Blinky class
//$declare${AOs::Nodo3} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Nodo3} ..............................................................
typedef struct Nodo3 {
// protected:
    QActive super;

// private:
    QTimeEvt timeEvt;

// public:

// private:
    QTimeEvt Evt_time300ms;
    QTimeEvt Evt_time3s;

// private state histories
    QStateHandler hist_Modo_Normal;
} Nodo3;

extern Nodo3 Nodo3_inst;

// protected:
static QState Nodo3_initial(Nodo3 * const me, void const * const par);
static QState Nodo3_Modo_Normal(Nodo3 * const me, QEvt const * const e);
static QState Nodo3_off(Nodo3 * const me, QEvt const * const e);
static QState Nodo3_Escritura(Nodo3 * const me, QEvt const * const e);
static QState Nodo3_Modo_Error(Nodo3 * const me, QEvt const * const e);
static QState Nodo3_timeout(Nodo3 * const me, QEvt const * const e);
//$enddecl${AOs::Nodo3} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${Shared} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::AO_Nodo3} ........................................................
QActive * const AO_Nodo3 = &Nodo3_inst.super;

//${Shared::Nodo3_ctor} ......................................................
void Nodo3_ctor(void) {
    Nodo3 * const me = &Nodo3_inst;
    QActive_ctor(&me->super, Q_STATE_CAST(&Nodo3_initial));

    /* Arma el evento de tiempo de 500ms. */
    QTimeEvt_ctorX(&me->timeEvt, &me->super, TIMEOUT_SIG, 0U);

    /* Arma el evento de tiempo de 300ms. */
    QTimeEvt_ctorX(&me->Evt_time300ms, &me->super, TIME_300MS_SIG, 0U);

    /* Arma el evento de tiempo de 3s. */
    //QTimeEvt_ctorX(&me->Evt_time3s, &me->super, RESET_CAN_SIG, 0U);
}
//$enddef${Shared} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${AOs::Nodo3} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Nodo3} ..............................................................
Nodo3 Nodo3_inst;

//${AOs::Nodo3::SM} ..........................................................
static QState Nodo3_initial(Nodo3 * const me, void const * const par) {
    //${AOs::Nodo3::SM::initial}
    // state history attributes
    me->hist_Modo_Normal = Q_STATE_CAST(&Nodo3_off);

    QS_FUN_DICTIONARY(&Nodo3_Modo_Normal);
    QS_FUN_DICTIONARY(&Nodo3_off);
    QS_FUN_DICTIONARY(&Nodo3_Escritura);
    QS_FUN_DICTIONARY(&Nodo3_Modo_Error);
    QS_FUN_DICTIONARY(&Nodo3_timeout);

    return Q_TRAN(&Nodo3_Modo_Normal);
}

//${AOs::Nodo3::SM::Modo_Normal} .............................................
static QState Nodo3_Modo_Normal(Nodo3 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Nodo3::SM::Modo_Normal}
        case Q_EXIT_SIG: {
            // save deep history
            me->hist_Modo_Normal = QHsm_state(Q_HSM_UPCAST(me));
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Nodo3::SM::Modo_Normal::initial}
        case Q_INIT_SIG: {
            QTimeEvt_armX(&me->timeEvt,
            BSP_TICKS_PER_SEC, BSP_TICKS_PER_SEC);
            status_ = Q_TRAN(&Nodo3_off);
            break;
        }
        //${AOs::Nodo3::SM::Modo_Normal::TIMEOUT_RX}
        case TIMEOUT_RX_SIG: {
            /* Activamos el temporizador de 300ms. */
            QTimeEvt_armX(&me->Evt_time300ms,
            BSP_TICKS_300MS/3 , BSP_TICKS_300MS/3);

            LED_RED_OFF();

            /* Activamos el temporizador de 3s. */
            //QTimeEvt_armX(&me->Evt_time3s,
            //BSP_TICKS_3S, BSP_TICKS_3S);
            status_ = Q_TRAN(&Nodo3_timeout);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::Nodo3::SM::Modo_Normal::off} ........................................
static QState Nodo3_off(Nodo3 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Nodo3::SM::Modo_Normal::off}
        case Q_ENTRY_SIG: {
            BSP_ledOff();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Nodo3::SM::Modo_Normal::off::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&Nodo3_Escritura);
            break;
        }
        default: {
            status_ = Q_SUPER(&Nodo3_Modo_Normal);
            break;
        }
    }
    return status_;
}

//${AOs::Nodo3::SM::Modo_Normal::Escritura} ..................................
static QState Nodo3_Escritura(Nodo3 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Nodo3::SM::Modo_Normal::Escritura}
        case Q_ENTRY_SIG: {
            /* Prendemos el led. */
            BSP_ledOn();

            /* Enviamos la informacion a la app. */
            Nodo3_salidaSerie();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Nodo3::SM::Modo_Normal::Escritura::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&Nodo3_off);
            break;
        }
        default: {
            status_ = Q_SUPER(&Nodo3_Modo_Normal);
            break;
        }
    }
    return status_;
}

//${AOs::Nodo3::SM::Modo_Error} ..............................................
static QState Nodo3_Modo_Error(Nodo3 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::Nodo3::SM::Modo_Error::timeout} .....................................
static QState Nodo3_timeout(Nodo3 * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Nodo3::SM::Modo_Error::timeout::RESET_CAN}
        case RESET_CAN_SIG: {
            // Se activa luego de 3 segundos
            /* Desactivamos los temporizadores. */
            QTimeEvt_disarm(&me->Evt_time300ms);
            //QTimeEvt_disarm(&me->Evt_time3s);

            LED_GREEN_OFF();
            status_ = Q_TRAN_HIST(me->hist_Modo_Normal);
            break;
        }
        //${AOs::Nodo3::SM::Modo_Error::timeout::TIME_300MS}
        case TIME_300MS_SIG: {
            /* Togglea el led verde. */
            LED_GREEN_TOGGLE();
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Nodo3_Modo_Error);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::Nodo3} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${AOs::setEvt_Timeout} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::setEvt_Timeout} .....................................................
void setEvt_Timeout(void) {
    // Crear el evento dinámicamente
    QEvt *evtTimeout = Q_NEW(QEvt, TIMEOUT_RX_SIG);  // El evento INICIO_SIG

    // Postear el evento a la máquina de estados de Blinky
    QACTIVE_POST(AO_Nodo3, evtTimeout, 0);
}
//$enddef${AOs::setEvt_Timeout} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${AOs::setEvt_ResetCan} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::setEvt_ResetCan} ....................................................
void setEvt_ResetCan(void) {
    // Crear el evento dinámicamente
    QEvt *evtResetCan = Q_NEW(QEvt, RESET_CAN_SIG);  // El evento RESET_CAN_SIG

    // Postear el evento a la máquina de estados de Blinky
    QACTIVE_POST(AO_Nodo3, evtResetCan, 0);
}
//$enddef${AOs::setEvt_ResetCan} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
