//$file${.::blinky.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: blinky_console.qm
// File:  ${.::blinky.c}
//
// This code has been generated by QM 6.1.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::blinky.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"    // QP/C real-time embedded framework
#include "bsp.h"    // Board Support Package interface

// ask QM to declare the Blinky class
//$declare${AOs::Blinky} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Blinky} .............................................................
typedef struct Blinky {
// protected:
    QActive super;

// private:
    QTimeEvt timeEvt;

// public:

// private state histories
    QStateHandler hist_Modo_Normal;
} Blinky;

extern Blinky Blinky_inst;

// protected:
static QState Blinky_initial(Blinky * const me, void const * const par);
static QState Blinky_Modo_Normal(Blinky * const me, QEvt const * const e);
static QState Blinky_Idle(Blinky * const me, QEvt const * const e);
static QState Blinky_Escritura(Blinky * const me, QEvt const * const e);
static QState Blinky_Modo_Error(Blinky * const me, QEvt const * const e);
static QState Blinky_timeout(Blinky * const me, QEvt const * const e);
//$enddecl${AOs::Blinky} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${Shared} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::AO_Blinky} .......................................................
QActive * const AO_Blinky = &Blinky_inst.super;

//${Shared::Blinky_ctor} .....................................................
void Blinky_ctor(void) {
    Blinky * const me = &Blinky_inst;
    QActive_ctor(&me->super, Q_STATE_CAST(&Blinky_initial));
    QTimeEvt_ctorX(&me->timeEvt, &me->super, TIMEOUT_SIG, 0U);
}
//$enddef${Shared} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${AOs::Blinky} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::Blinky} .............................................................
Blinky Blinky_inst;

//${AOs::Blinky::SM} .........................................................

//${AOs::Blinky::SM::Modo_Normal} ............................................
static QState Blinky_Modo_Normal(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Blinky::SM::Modo_Normal}
        case Q_EXIT_SIG: {
            // save deep history
            me->hist_Modo_Normal = QHsm_state(Q_HSM_UPCAST(me));
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Blinky::SM::Modo_Normal::initial}
        case Q_INIT_SIG: {
            (void)par; // unused parameter
            QTimeEvt_armX(&me->timeEvt,
            BSP_TICKS_PER_SEC/2, BSP_TICKS_PER_SEC/2);
            status_ = Q_TRAN(&Blinky_Idle);
            break;
        }
        //${AOs::Blinky::SM::Modo_Normal::TIMEOUT_RX}
        case TIMEOUT_RX_SIG: {
            status_ = Q_TRAN(&Blinky_timeout);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::Blinky::SM::Modo_Normal::Idle} ......................................
static QState Blinky_Idle(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Blinky::SM::Modo_Normal::Idle}
        case Q_ENTRY_SIG: {
            BSP_ledOff();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Blinky::SM::Modo_Normal::Idle::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&Blinky_Escritura);
            break;
        }
        default: {
            status_ = Q_SUPER(&Blinky_Modo_Normal);
            break;
        }
    }
    return status_;
}

//${AOs::Blinky::SM::Modo_Normal::Escritura} .................................
static QState Blinky_Escritura(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Blinky::SM::Modo_Normal::Escritura}
        case Q_ENTRY_SIG: {
            /* Prendemos el led. */
            BSP_ledOn();

            /* Enviamos la informacion a la app. */
            Nodo3_salidaSerie();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::Blinky::SM::Modo_Normal::Escritura::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&Blinky_Idle);
            break;
        }
        default: {
            status_ = Q_SUPER(&Blinky_Modo_Normal);
            break;
        }
    }
    return status_;
}

//${AOs::Blinky::SM::Modo_Error} .............................................
static QState Blinky_Modo_Error(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Blinky::SM::Modo_Error::initial}
        case Q_INIT_SIG: {
            status_ = Q_TRAN(&Blinky_timeout);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::Blinky::SM::Modo_Error::timeout} ....................................
static QState Blinky_timeout(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::Blinky::SM::Modo_Error::timeout::RESET_CAN}
        case RESET_CAN_SIG: {
            // Se activa luego de 3 segundos
            status_ = Q_TRAN_HIST(me->hist_Modo_Normal);
            break;
        }
        //${AOs::Blinky::SM::Modo_Error::timeout::TIME_300MS}
        case TIME_300MS_SIG: {
            /* Togglea el led verde. */
            LED_GREEN_TOGGLE();
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Blinky_Modo_Error);
            break;
        }
    }
    return status_;
}
//$enddef${AOs::Blinky} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
