//$file${.::blinky.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: Nodo2.qm
// File:  ${.::blinky.c}
//
// This code has been generated by QM 6.1.1 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::blinky.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "blinky.h"
#include "qpc.h"

#include "fsl_debug_console.h"

//#include "safe_std.h" // portable "safe" <stdio.h>/<string.h> facilities
#include <stdlib.h> // for exit()

//Q_DEFINE_THIS_FILE

#ifdef Q_SPY
    #error Simple Blinky Application does not provide Spy build configuration
#endif

//..........................................................................
Q_NORETURN Q_onError(char const * const module, int_t const id) {
    PRINTF("\n\rERROR in %s:%d", module, id);
    exit(-1);
}
//..........................................................................
void assert_failed(char const * const module, int_t const id); // prototype
void assert_failed(char const * const module, int_t const id) {
    Q_onError(module, id);
}
//..........................................................................
void QF_onStartup(void) {}
//..........................................................................
void QF_onCleanup(void) {}
//............................................................................
void QV_onIdle(void) { /* entered with interrupts DISABLED, see NOTE01 */
#if defined NDEBUG
     /* Put the CPU and peripherals to the low-power mode */
    QV_CPU_SLEEP(); /* atomically go to sleep and enable interrupts */
#else
    QF_INT_ENABLE(); /* just enable interrupts */
#endif
}
//..........................................................................
void QF_onClockTick(void) {
    QTIMEEVT_TICK_X(0U, (void *)0);  // clock tick processing
}
//..........................................................................
void BSP_ledOff(void) {
    PRINTF("\n\r%s\n", "LED OFF");
}
//..........................................................................
void BSP_ledOn(void) {
    PRINTF("\n\r%s\n", "LED ON");
}
//..........................................................................
void BSP_initMsg(void)
{
    PRINTF("\nNombre: Nodo 2\n\r");
    PRINTF("Descripcion: Este nodo se encarga de producir un "
                "valor de los estados de sus perifericos y ademas"
                "obtener datos del ldr proveniente de otro modulo"
                "can. Ademas cuenta con un Id=20.\n\r");
    PRINTF("Materia: Sistemas digitales 2\n\r");

    return;
}
