//$file${.::Nodo_2.h} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: Nodo2.qm
// File:  ${.::Nodo_2.h}
//
// This code has been generated by QM 6.1.1 <www.state-machine.com/qm>.
// DO NOT EDIT SECTIONS BETWEEN THE COMMENTS "$...vvv".."$end...^^^".
// All your changes in these sections will be lost.
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open source software: you can redistribute it under
// the terms of the GNU General Public License as published by the Free
// Software Foundation.
//
// This code is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
// more details.
//
// NOTE:
// Alternatively, this generated code may be distributed under the terms
// of Quantum Leaps commercial licenses, which expressly supersede the GNU
// General Public License and are specifically designed for licensees
// interested in retaining the proprietary status of their code.
//
// Contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::Nodo_2.h} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/*
 * Nodo_2.h
 *
 *  Created on: 14 sep. 2024
 *      Author: agustin
 */

#ifndef NODO_2_H_
#define NODO_2_H_

#define TIEMPO_DE_MUESTRA_ESTADOS	1000

/**
 * @brief Inicializacion del Nodo 2
 */
extern void Nodo2_init(void);
/**
 * @brief Escritura del modulo can.
 */
extern void Nodo2_writeToBus(void);
/**
 * @brief Lectura del modulo can.
 */
extern void Nodo2_serialPort(void);
/**
 * @brief Transferencia de nodo 2.
 */
extern void Nodo2_xtransfer(void);

#endif /* NODO_2_H_ */
