//$file${.::MEF.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
//
// Model: MEF_kl46z.qm
// File:  ${.::MEF.c}
//
// This code has been generated by QM 7.0.0 <www.state-machine.com/qm>.
// DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
//
// Copyright (c) 2005 Quantum Leaps, LLC. All rights reserved.
//
//                 ____________________________________
//                /                                   /
//               /    GGGGGGG    PPPPPPPP   LL       /
//              /   GG     GG   PP     PP  LL       /
//             /   GG          PP     PP  LL       /
//            /   GG   GGGGG  PPPPPPPP   LL       /
//           /   GG      GG  PP         LL       /
//          /     GGGGGGG   PP         LLLLLLL  /
//         /___________________________________/
//
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This generated code is open-source software licensed under the GNU
// General Public License (GPL) as published by the Free Software Foundation
// (see <https://www.gnu.org/licenses>).
//
// NOTE:
// The GPL does NOT permit the incorporation of this code into proprietary
// programs. Please contact Quantum Leaps for commercial licensing options,
// which expressly supersede the GPL and are designed explicitly for
// closed-source distribution.
//
// Quantum Leaps contact information:
// <www.state-machine.com/licensing>
// <info@state-machine.com>
//
//$endhead${.::MEF.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#include "qpc.h"    // QP/C real-time embedded framework
#include "bsp.h"    // Board Support Package interface

#include "fsl_debug_console.h"
#include "board.h"

//$declare${AOs} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::MEF} ................................................................
typedef struct MEF {
// protected:
    QActive super;

// public:

// private:
    QTimeEvt timeEvt;
    QTimeEvt time1sEvt;
    QTimeEvt time2sEvt;
    QTimeEvt time3sEvt;

// private state histories
    QStateHandler hist_MEF_Semaforo;
} MEF;

extern MEF MEF_inst;

// protected:
static QState MEF_initial(MEF * const me, void const * const par);
static QState MEF_MEF_Semaforo(MEF * const me, QEvt const * const e);
static QState MEF_Est_reset(MEF * const me, QEvt const * const e);
static QState MEF_Est_Rojo(MEF * const me, QEvt const * const e);
static QState MEF_Est_Amarillo(MEF * const me, QEvt const * const e);
static QState MEF_Est_Verde(MEF * const me, QEvt const * const e);
static QState MEF_MEF_Emergencia(MEF * const me, QEvt const * const e);
static QState MEF_Est_Emerg_reset(MEF * const me, QEvt const * const e);
static QState MEF_Est_Intermitente(MEF * const me, QEvt const * const e);

//${AOs::estANT} .............................................................
typedef enum estANT {
    Est_ROJO = 0,
    Est_VERDE,
}estANT;

//${AOs::guardCond1} .........................................................
static bool guardCond1(void);

//${AOs::estActual} ..........................................................
extern estANT estActual;

//${AOs::evtEmergencia} ......................................................
extern QEvt const evtEmergencia;

//${AOs::evtTRIG1} ...........................................................
extern QEvt const evtTRIG1;
//$enddecl${AOs} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$declare ${AOs::MEF}

//$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
// Check for the minimum required QP version
#if (QP_VERSION < 730U) || (QP_VERSION != ((QP_RELEASE^4294967295U)%0x2710U))
#error qpc version 7.3.0 or higher required
#endif
//$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
//$define${Shared} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${Shared::AO_MEF} ..........................................................
QActive * const AO_MEF = &MEF_inst.super;

//${Shared::MEF_ctor} ........................................................
void MEF_ctor(void) {
    MEF * const me = &MEF_inst;

    // Construye el objeto activo
    QActive_ctor(&me->super, Q_STATE_CAST(&MEF_initial));

    // Construye los timers
    QTimeEvt_ctorX(&me->timeEvt, &me->super, TIMEOUT_SIG, 0U);
    QTimeEvt_ctorX(&me->time1sEvt, &me->super, TIMER1S_SIG, 0U);
    QTimeEvt_ctorX(&me->time2sEvt, &me->super, TIMER2S_SIG, 0U);
    QTimeEvt_ctorX(&me->time3sEvt, &me->super, TIMER3S_SIG, 0U);
}

//${Shared::MEF_setEvtEmergencia} ............................................
void MEF_setEvtEmergencia(void) {
    QACTIVE_POST(AO_MEF, &evtEmergencia, 0U);
}
//$enddef${Shared} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

//$define${AOs} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

//${AOs::MEF} ................................................................
MEF MEF_inst;

//${AOs::MEF::SM} ............................................................
static QState MEF_initial(MEF * const me, void const * const par) {
    //${AOs::MEF::SM::initial}
    // state history attributes
    me->hist_MEF_Semaforo = Q_STATE_CAST(&MEF_Est_Rojo);

    QS_FUN_DICTIONARY(&MEF_MEF_Semaforo);
    QS_FUN_DICTIONARY(&MEF_Est_reset);
    QS_FUN_DICTIONARY(&MEF_Est_Rojo);
    QS_FUN_DICTIONARY(&MEF_Est_Amarillo);
    QS_FUN_DICTIONARY(&MEF_Est_Verde);
    QS_FUN_DICTIONARY(&MEF_MEF_Emergencia);
    QS_FUN_DICTIONARY(&MEF_Est_Emerg_reset);
    QS_FUN_DICTIONARY(&MEF_Est_Intermitente);

    return Q_TRAN(&MEF_MEF_Semaforo);
}

//${AOs::MEF::SM::MEF_Semaforo} ..............................................
static QState MEF_MEF_Semaforo(MEF * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::MEF::SM::MEF_Semaforo}
        case Q_EXIT_SIG: {
            // save deep history
            me->hist_MEF_Semaforo = QHsm_state(Q_HSM_UPCAST(me));
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::MEF::SM::MEF_Semaforo::initial}
        case Q_INIT_SIG: {
            QTimeEvt_armX(&me->timeEvt,
            BSP_TICKS_PER_SEC, 0);
            status_ = Q_TRAN(&MEF_Est_reset);
            break;
        }
        //${AOs::MEF::SM::MEF_Semaforo::EMERGENCIA}
        case EMERGENCIA_SIG: {
            status_ = Q_TRAN(&MEF_MEF_Emergencia);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::MEF::SM::MEF_Semaforo::Est_reset} ...................................
static QState MEF_Est_reset(MEF * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::MEF::SM::MEF_Semaforo::Est_reset}
        case Q_ENTRY_SIG: {
            // Apaga todos los leds
            BSP_ledOff();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::MEF::SM::MEF_Semaforo::Est_reset}
        case Q_EXIT_SIG: {
            // Desarma el temp.
            QTimeEvt_disarm(&me->timeEvt);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::MEF::SM::MEF_Semaforo::Est_reset::TIMEOUT}
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&MEF_Est_Rojo);
            break;
        }
        default: {
            status_ = Q_SUPER(&MEF_MEF_Semaforo);
            break;
        }
    }
    return status_;
}

//${AOs::MEF::SM::MEF_Semaforo::Est_Rojo} ....................................
static QState MEF_Est_Rojo(MEF * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::MEF::SM::MEF_Semaforo::Est_Rojo}
        case Q_ENTRY_SIG: {
            // Prende led
            PRINTF("LED ROJO ON\n\r");
            LED_RED_ON();
            estActual = Est_ROJO;
            // Arma el temporizador de 2 segundos
            QTimeEvt_armX(&me->time2sEvt, BSP_TICKS_PER_SEC*2, 0);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::MEF::SM::MEF_Semaforo::Est_Rojo}
        case Q_EXIT_SIG: {
            // Apaga led
            LED_RED_OFF();
            // Desarma el temporizador de 2 segundos
            QTimeEvt_disarm(&me->time2sEvt);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::MEF::SM::MEF_Semaforo::Est_Rojo::TIMER2S}
        case TIMER2S_SIG: {
            status_ = Q_TRAN(&MEF_Est_Amarillo);
            break;
        }
        default: {
            status_ = Q_SUPER(&MEF_MEF_Semaforo);
            break;
        }
    }
    return status_;
}

//${AOs::MEF::SM::MEF_Semaforo::Est_Amarillo} ................................
static QState MEF_Est_Amarillo(MEF * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::MEF::SM::MEF_Semaforo::Est_Amarillo}
        case Q_ENTRY_SIG: {
            // Prende led
            PRINTF("LED AMARILLO ON\n\r");
            // Arma temp. 1 segundo
            QTimeEvt_armX(&me->time1sEvt, BSP_TICKS_PER_SEC*1, 0);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::MEF::SM::MEF_Semaforo::Est_Amarillo}
        case Q_EXIT_SIG: {
            // Apaga led

            // Desarma temp. 1 segundo
            QTimeEvt_disarm(&me->time1sEvt);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::MEF::SM::MEF_Semaforo::Est_Amarillo::TIMER1S}
        case TIMER1S_SIG: {
            //${AOs::MEF::SM::MEF_Semaforo::Est_Amarillo::TIMER1S::[VERDE]}
            if (guardCond1()) {
                status_ = Q_TRAN(&MEF_Est_Verde);
            }
            //${AOs::MEF::SM::MEF_Semaforo::Est_Amarillo::TIMER1S::[ROJO]}
            else {
                status_ = Q_TRAN(&MEF_Est_Rojo);
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&MEF_MEF_Semaforo);
            break;
        }
    }
    return status_;
}

//${AOs::MEF::SM::MEF_Semaforo::Est_Verde} ...................................
static QState MEF_Est_Verde(MEF * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::MEF::SM::MEF_Semaforo::Est_Verde}
        case Q_ENTRY_SIG: {
            // Prende led
            PRINTF("LED VERDE ON\n\r");
            LED_GREEN_ON();
            estActual = Est_VERDE;
            // Arma temp. 3 segundos
            QTimeEvt_armX(&me->time3sEvt, BSP_TICKS_PER_SEC*3, 0);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::MEF::SM::MEF_Semaforo::Est_Verde}
        case Q_EXIT_SIG: {
            // Apaga led
            LED_GREEN_OFF();
            // Desarma temp. 3 segundos
            QTimeEvt_disarm(&me->time3sEvt);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::MEF::SM::MEF_Semaforo::Est_Verde::TIMER3S}
        case TIMER3S_SIG: {
            status_ = Q_TRAN(&MEF_Est_Amarillo);
            break;
        }
        default: {
            status_ = Q_SUPER(&MEF_MEF_Semaforo);
            break;
        }
    }
    return status_;
}

//${AOs::MEF::SM::MEF_Emergencia} ............................................
static QState MEF_MEF_Emergencia(MEF * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::MEF::SM::MEF_Emergencia::initial}
        case Q_INIT_SIG: {
            status_ = Q_TRAN(&MEF_Est_Emerg_reset);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

//${AOs::MEF::SM::MEF_Emergencia::Est_Emerg_reset} ...........................
static QState MEF_Est_Emerg_reset(MEF * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::MEF::SM::MEF_Emergencia::Est_Emerg_reset}
        case Q_ENTRY_SIG: {
            // Arma el evento
            PRINTF("Emergencia!!!\n\r");
            QACTIVE_POST(AO_MEF, &evtTRIG1, 0U);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::MEF::SM::MEF_Emergencia::Est_Emerg_reset::TRIG1}
        case TRIG1_SIG: {
            status_ = Q_TRAN(&MEF_Est_Intermitente);
            break;
        }
        default: {
            status_ = Q_SUPER(&MEF_MEF_Emergencia);
            break;
        }
    }
    return status_;
}

//${AOs::MEF::SM::MEF_Emergencia::Est_Intermitente} ..........................
static QState MEF_Est_Intermitente(MEF * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        //${AOs::MEF::SM::MEF_Emergencia::Est_Intermitente}
        case Q_ENTRY_SIG: {
            // Arma el temp.
            QTimeEvt_armX(&me->timeEvt,
            BSP_TICKS_PER_SEC, BSP_TICKS_PER_SEC/2);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::MEF::SM::MEF_Emergencia::Est_Intermitente}
        case Q_EXIT_SIG: {
            // Desarma el temp.
            LED_RED_OFF();
            QTimeEvt_disarm(&me->timeEvt);
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::MEF::SM::MEF_Emergencia::Est_Intermitente::TIMEOUT}
        case TIMEOUT_SIG: {
            // Toggle led
            //PRINTF("Toggle ROJO\n\r");
            LED_RED_TOGGLE();
            status_ = Q_HANDLED();
            break;
        }
        //${AOs::MEF::SM::MEF_Emergencia::Est_Intermitente::EMERGENCIA}
        case EMERGENCIA_SIG: {
            status_ = Q_TRAN_HIST(me->hist_MEF_Semaforo);
            break;
        }
        default: {
            status_ = Q_SUPER(&MEF_MEF_Emergencia);
            break;
        }
    }
    return status_;
}

//${AOs::guardCond1} .........................................................
static bool guardCond1(void) {
    return estActual==Est_ROJO? true:false;
}

//${AOs::estActual} ..........................................................
estANT estActual = Est_ROJO;

//${AOs::evtEmergencia} ......................................................
QEvt const evtEmergencia = QEVT_INITIALIZER(EMERGENCIA_SIG);

//${AOs::evtTRIG1} ...........................................................
QEvt const evtTRIG1 = QEVT_INITIALIZER(TRIG1_SIG);
//$enddef${AOs} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
